name: Update v1 Tag

on:
  workflow_dispatch:

jobs:
  update-v1-tag:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Generate token
        uses: actions/create-github-app-token@v2
        id: create-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write

      - name: Configure git
        env:
          TOKEN: ${{ steps.create-app-token.outputs.token }}
          REPOSITORY: ${{ github.repository }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${REPOSITORY}"

      - name: Update v1 tag
        run: |
          git tag -d v1 || true
          git push origin :refs/tags/v1 || true
          git tag v1
          git push origin v1
